### PR TITLE
Fixed checkbox rendering

### PR DESCRIPTION
**Pull request by beckyconning**
Part of a fix for https://slamdata.atlassian.net/browse/SD-1302

### CODE REVIEW

**Comment by jonsterling** [comment]
Looking ~~food~~ good :+1: 

I assume that this depends on https://github.com/slamdata/purescript-markdown/pull/50 to work properly? If so, let's merge it in after a new version of `purescript-markdown` has been released, and the lower bound for the dependency has been updated here.

**Comment by garyb** [comment]
:spaghetti: :curry: :stew:

Yeah, it does depend on that being merged first, so :+1: for bumping lower bound on this before merging.

**Comment by jonsterling** [comment]
@garyb lmao, it took me several seconds to figure out why you were posting all these food emoji...

**Comment by garyb** [comment]
:smile: I like it. We should start using food rather than :+1: and :shipit:, there's much more variety!

**Comment by garyb** [comment]
@jonsterling I guess we should incorporate this one while we're at it?

**Comment by jonsterling** [comment]
@garyb Yeah!

@beckyconning Are you ok with merging this now? It's been sitting for a bit, and I wanted to make sure you hadn't changed your mind about this change.

**Comment by garyb** [comment]
I think we need to bump the lower bound for `markdown` to `^1.12.1` too.

**Comment by jonsterling** [comment]
@garyb :+1:

**Pull request merged**
