### PR TITLE
Add Functor SlamDownFormState; upgrade purescript-markdown

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by jonsterling** [comment]
No need to rush on the review for this, since I won't need it urgently until monday.

**Comment by jonsterling** [comment]
@cryogenian can you review this when you have time? (the change is just to add a `Functor` instance, very straightforward). No need to rush, I won't need this till some point on Monday.

**Comment by cryogenian** [comment]
:+1:

**Comment by jonsterling** [comment]
I think that this can be considered a patch version update, because it cannot introduce any incompatibilities:

Consider the case where a client has implemented `Functor SlamDownFormState`; either, the client is `Prelude` itself, or it is an orphan instance. The first case is obviously false, and we do not permit orphans.

**Comment by jonsterling** [comment]
Oh, never mind; we bumped the version of the `purescript-markdown` dep, so this will have to be at least a minor version bump too.

**Comment by garyb** [comment]
There's a major halogen bump that everything is missing since we added `transitionend` too, so they both might need that too.

**Comment by jonsterling** [comment]
@garyb Oh, good to know; I can update this lib to the new halogen today.

**Comment by garyb** [comment]
Yeah, this is one that needs an update actually. 0.7.0 is the latest Halogen I think.

**Comment by jonsterling** [comment]
@garyb Ah, there's also `purescript-ace-halogen`; I'm taking care of that now as well.

**Pull request merged**
