### PR TITLE
[SD-1371] Adjust behavior of dropdowns to comport with radio buttons

### PR DESCRIPTION
**Pull request by jonsterling**
- remove empty state that was added to the list
- add the default value to the list if it is not already present

This should resolve [SD-1371](https://slamdata.atlassian.net/browse/SD-1371) (see discussion in [SD-1360](https://slamdata.atlassian.net/browse/SD-1360).

### CODE REVIEW

**Comment by garyb** [comment]
Build failure?

**Comment by garyb** [comment]
Oh, it's that timeout thing you mentioned yesterday... hmm.

**Comment by jonsterling** [comment]
@garyb Looks like it might have been a travis issue (build hung); I'm running it again...

**Comment by garyb** [comment]
Code change looks good to me though :tangerine:

**Comment by jonsterling** [comment]
@garyb thanks!

On the side, I really don't understand what could cause the build to hang so frequently at that point... It's very strange that it only happens in Travis (so far).

**Comment by jonsterling** [comment]
Ok, between my fork and the main repo, that's three times in a row this build has failed; I'm really at a loss. It works fine on my machine...

**Comment by jonsterling** [comment]
~~I wonder if the problem was some kind of deadlock or something in `gulp`.~~ Well, not `gulp` necessarily I suppose, since I had it happen with `pulp` yesterday.

**Comment by jonsterling** [comment]
OK, I don't really understand what's going on with Travis, but I'm going to stick with what I've got now, because it appears to work (for some unknown reason).

**Comment by garyb** [comment]
It's pretty annoying this has started happening, considering we've not moved to psc 0.8 or anything "major" like that...

**Comment by jonsterling** [comment]
@garyb Yeah... And one thing I'm surprised by is that this seems to mostly occur (very frequently) on our libraries, but not on SlamData itself. SlamData also builds way faster than these libraries, for some reason (IME). Are we doing something different?

**Comment by jonsterling** [comment]
I'm squashing everything except the travis "fix" commit, since I want that to be in the commit log so that we can find it later if necessary.

**Pull request merged**
