### PR TITLE
Render consecutive form fields as a form set

### PR DESCRIPTION
**Pull request by natefaubion**
screen shot 2017-02-27 at 4 20 57 pm

### CODE REVIEW

**Comment by garyb** [comment]
Code looks good, but is that screenshot right - it looks like the second label is truncated, unless it really did say that?

**Comment by natefaubion** [comment]
It really did say that, sorry 😆

**Review by garyb — APPROVED** [review]
Haha, ok :smile:

**Comment by natefaubion** [comment]
It was previously longer, but I truncated it at some point for purposes of testing :)

**Pull request merged**
